version: 0.2

env:
  variables:
    CODEARTIFACT_DOMAIN: network
    CODEARTIFACT_DOMAIN_OWNER: "767044641724"
    CODEARTIFACT_REPO: nextwork-devops-cicd
    AWS_DEFAULT_REGION: eu-central-1

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - set -euxo pipefail
      - echo "Java:" && java -version
      - echo "Maven:" && mvn -v
      # Get CodeArtifact token
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain "$CODEARTIFACT_DOMAIN" \
          --domain-owner "$CODEARTIFACT_DOMAIN_OWNER" \
          --query authorizationToken --output text \
          --region "$AWS_DEFAULT_REGION")
      # Minimal Maven settings that reference the token
      - mkdir -p ~/.m2
      - |
        cat > ~/.m2/settings.xml <<'XML'
        <settings>
          <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>${env.CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
        </settings>
        XML
      - CA_URL="https://${CODEARTIFACT_DOMAIN}-${CODEARTIFACT_DOMAIN_OWNER}.d.codeartifact.${AWS_DEFAULT_REGION}.amazonaws.com/maven/${CODEARTIFACT_REPO}/"
      - echo "Publishing to: $CA_URL"
  build:
    commands:
      - mvn -B -DskipTests -s ~/.m2/settings.xml \
          -DaltDeploymentRepository=codeartifact::default::"$CA_URL" \
          clean package deploy
  post_build:
    commands:
      - echo "Build finished on $(date)"

artifacts:
  files:
    - target/*.war
  discard-paths: true
